export { default as github } from './github-white.svg'
export { default as linkedin } from './linkedin-white.svg'
export { default as twitter } from './twitter-white.svg'
export { default as donation } from './donation2.svg'
export { default as info } from './info.svg'
