export { default as azadBackPic } from './azad-back.png'
export { default as azadDeskPic } from './azad-desk.png'
export { default as azadConfusedPic } from './azad-confused.png'
export { default as cashPic } from "./cash2.png"
export { default as chatPic } from "./chat.png"
export { default as cincinnatusPic } from "./cincinnatus.jpg"
export { default as classifiedPic } from "./classified.png"
export { default as decorPic } from "./decor2.png"
export { default as documentPic } from "./classified-document.png"
export { default as equipmentPic } from "./equipment.jpg"
export { default as friendsPic } from "./friends3.png"
export { default as groupfriendsPic } from "./friends4.png"
export { default as journalPic } from './journal18oct.png'
export { default as kiosquePic } from './kiosque.png'
export { default as lockerPic } from "./locker.png"
export { default as lurembergPic } from './luremberg2.jpg'
export { default as manReadJournalPic } from "./manreadjournal.png"
export { default as notifPic } from "./notif.png"
export { default as paymentPic } from "./payment.png"
export { default as phonePic } from "./onthephone.png"
export { default as pickupPic } from "./pickup2.png"
export { default as redactionPic } from "./newsroom1.png"
export { default as refusedPic } from "./refused.png"
export { default as skylerHomePic } from "./skyler-place.png"
export { default as skylerPic } from "./skylerDesk.png"
export { default as takeawayPic } from "./takeaway2.png"
export { default as tassePic } from './tasse.png'
export { default as tvPic } from './tv.png'
export { default as pubPic } from './pub.png'
